---
env:
  browser: true
  es6: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  arrow-parens: [error, 'as-needed']
  no-restricted-syntax: [off]
